In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df =pd.read_csv('/kaggle/input/life-expectancy-and-socio-economic-world-bank/life expectancy.csv')

In [ ]:
df.head(2)

In [ ]:
df.tail(2)

In [ ]:
df.info()

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
df.isnull().sum()

In [ ]:
df.describe()

In [ ]:
df['Region'].value_counts()

In [ ]:
country_distribution_by_Region = df['Region'].value_counts() 
plt.figure(figsize=(18,6))
sns.barplot(x=country_distribution_by_Region.index, y=country_distribution_by_Region.values, palette='rainbow')
plt.ylabel('Count', color='green', size=20)
plt.xlabel('Region', color='green', size=20)
plt.title('No. of country from each continent', color='red', size=22)
plt.xticks(rotation=45)  # Rotate the channel types for better readability

plt.show()

In [ ]:
country_distribution_by_Region = df['Region'].value_counts()
plt.figure(figsize=(13,13))
country_distribution_by_Region.plot(kind='pie', autopct='%1.1f%%', startangle=360, colors=plt.cm.Paired.colors)

# Create a pie chart
plt.title('Distribution of country by Region',color='indigo',size=20)
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle

plt.show()

In [ ]:
df['IncomeGroup'].value_counts()

In [ ]:
country_distribution_by_IncomeGroup = df['IncomeGroup'].value_counts() 
plt.figure(figsize=(18,6))
sns.barplot(x=country_distribution_by_IncomeGroup.index, y=country_distribution_by_IncomeGroup.values, palette='rainbow')
plt.ylabel('Count', color='green', size=20)
plt.xlabel('IncomeGroup', color='green', size=20)
plt.title('No. of country from each Income Group', color='red', size=22)
plt.xticks(rotation=45)  # Rotate the channel types for better readability

plt.show()

In [ ]:
country_distribution_by_IncomeGroup = df['IncomeGroup'].value_counts()
plt.figure(figsize=(13,13))
country_distribution_by_IncomeGroup.plot(kind='pie', autopct='%1.1f%%', startangle=360, colors=plt.cm.Paired.colors)

# Create a pie chart
plt.title('Distribution of country by Income Group',color='indigo',size=20)
plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle

plt.show()

In [ ]:
df.rename(columns={'Country Name':'country'},inplace=True)

In [ ]:
df['Year'].unique()

In [ ]:
#df[df['country'] == 'India'].values

In [ ]:
df['country'].unique()

# Life Expectancy

In [ ]:
highest_Life_Expectancy_country = df[['country', 'Year', 'Life Expectancy World Bank']].sort_values(by='Life Expectancy World Bank', ascending=False).head(5)
highest_Life_Expectancy_country

In [ ]:
highest_Life_Expectancy_count = df.loc[df['Life Expectancy World Bank'].idxmax()]['Life Expectancy World Bank']
print(f'Highest Life Expectancy Value : {highest_Life_Expectancy_count}')

In [ ]:
highest_Life_Expectancy_country = df.loc[df['Life Expectancy World Bank'].idxmax()]['country']
print(f'Highest Life Expectancy country : {highest_Life_Expectancy_country}')

In [ ]:
lowest_Life_Expectancy_country = df[['country', 'Year', 'Life Expectancy World Bank']].sort_values(by='Life Expectancy World Bank', ascending=True).head(5)
lowest_Life_Expectancy_country

In [ ]:
lowest_Life_Expectancy_country = df.loc[df['Life Expectancy World Bank'].idxmin()]['country']
print(f'Lowest Life Expectancy country : {lowest_Life_Expectancy_country}')

In [ ]:
lowest_Life_Expectancy_count = df.loc[df['Life Expectancy World Bank'].idxmin()]['Life Expectancy World Bank']
print(f'Lowest Life Expectancy Value : {lowest_Life_Expectancy_count}')

In [ ]:
# 1. Filter rows for 'India'
India_df = df[df['country'] == 'India']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
India_df = India_df[India_df['Year'].isin(years)]

# 3. Create a line plot for Life Expectancy over the years
plt.figure(figsize=(16, 6))
plt.plot(India_df['Year'].values, India_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='green')
plt.title('Life Expectancy of India (2001-2019)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Life Expectancy', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.tight_layout()
plt.show()

In [ ]:
# 1. Filter rows for 'Japan'
Japan_df = df[df['country'] == 'Japan']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
Japan_df = Japan_df[Japan_df['Year'].isin(years)]

# 3. Create a line plot for Life Expectancy over the years
plt.figure(figsize=(16, 6))
plt.plot(Japan_df['Year'].values, Japan_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='green')
plt.title('Life Expectancy of Japan (2001-20219)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Life Expectancy', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.tight_layout()
plt.show()

In [ ]:
# 1. Filter rows for 'China'
china_df = df[df['country'] == 'China']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
china_df = china_df[china_df['Year'].isin(years)]

# 3. Create a line plot for Life Expectancy over the years
plt.figure(figsize=(16, 6))
plt.plot(china_df['Year'].values, china_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='lime')
plt.title('Life Expectancy of China  (2001-20219)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Life Expectancy', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.tight_layout()
plt.show()

In [ ]:
# 1. Filter rows for 'USA'
USA_df = df[df['country'] == 'United States']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
USA_df = USA_df[USA_df['Year'].isin(years)]

# 3. Create a line plot for Life Expectancy over the years
plt.figure(figsize=(16, 6))
plt.plot(USA_df['Year'].values, USA_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='red')
plt.title('Life Expectancy of United States of America (2001-20219)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Life Expectancy', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.tight_layout()
plt.show()

In [ ]:
# 1. Filter rows for 'India & Pakistan'
India_df = df[df['country'] == 'India']
Pak_df = df[df['country'] == 'Pakistan']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
India_df = India_df[India_df['Year'].isin(years)]
Pak_df = Pak_df[Pak_df['Year'].isin(years)]

# 3. Create a line plot for Unemployment over the years
plt.figure(figsize=(16, 6))
plt.plot(India_df['Year'].values, India_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='magenta', label='India')
plt.plot(India_df['Year'].values, Pak_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='green', label='Pakistan')
plt.title('Life Expectancy comparison between India & Pakistan (2001-2019)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Life Expectancy', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()
plt.tight_layout()
plt.show()

Life Expectancy Comparison among Japan, china, USA, India, UK, France

In [ ]:
# 1. Filter rows for 'Japan, USA, China, India, UK, France'
Japan_df = df[df['country'] == 'Japan']
USA_df = df[df['country'] == 'United States']
China_df = df[df['country'] == 'China']
India_df = df[df['country'] == 'India']
UK_df = df[df['country'] == 'United Kingdom']
france_df = df[df['country'] == 'France']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
Japan_df = Japan_df[Japan_df['Year'].isin(years)]
China_df = China_df[China_df['Year'].isin(years)]
USA_df = USA_df[USA_df['Year'].isin(years)]
India_df = India_df[India_df['Year'].isin(years)]
UK_df = UK_df[UK_df['Year'].isin(years)]
france_df = france_df[france_df['Year'].isin(years)]

# 3. Create a line plot for Life Expectancy over the years
plt.figure(figsize=(16, 6))
plt.plot(Japan_df['Year'].values, Japan_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='green', label='Japan')
plt.plot(Japan_df['Year'].values, USA_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='purple', label='USA')
plt.plot(Japan_df['Year'].values, China_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='blue', label='China')
plt.plot(Japan_df['Year'].values, India_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='orange', label='India')
plt.plot(Japan_df['Year'].values, UK_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='cyan', label='United Kingdom')
plt.plot(Japan_df['Year'].values, france_df['Life Expectancy World Bank'].values, marker='o', linestyle='-', color='magenta', label='France')
plt.title('Life Expectancy comparison of Japan, USA, China, India, UK & France (2001-20219)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Life Expectancy', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()   # Add legend to distinguish between Japan and India
plt.tight_layout()
plt.show()

In [ ]:
# Create a bar graph
sns.set_style('darkgrid')
plt.figure(figsize=(16,10))
data=df.sort_values(by='Life Expectancy World Bank', ascending=False).head(600)
sns.barplot(y='country', x='Life Expectancy World Bank', data=data)
plt.xlabel('Life Expectancy World Bank ', color='green', size=40)
plt.ylabel('Country', color='green', size=40)
plt.title('Life Expectancy data for each Country', color='red',size=40)

In [ ]:
# Create a bar graph
sns.set_style('darkgrid')
plt.figure(figsize=(16,10))
data=df.sort_values(by='Life Expectancy World Bank', ascending=True).head(600)
sns.barplot(y='country', x='Life Expectancy World Bank', data=data)
plt.xlabel('Life Expectancy World Bank ', color='green', size=40)
plt.ylabel('Country', color='green', size=40)
plt.title('Life Expectancy data for each Country', color='red',size=40)

# Unemployment

In [ ]:
highest_Unemployment_country = df[['country', 'Year', 'Unemployment']].sort_values(by='Unemployment', ascending=False).head(5)
highest_Unemployment_country

In [ ]:
highest_Unemployment_country = df.loc[df['Unemployment'].idxmax()]['country']
print(f'highest Unemployment country : {highest_Unemployment_country}')

In [ ]:
lowest_Unemployment_country = df[['country', 'Year', 'Unemployment']].sort_values(by='Unemployment', ascending=True).head(5)
lowest_Unemployment_country

In [ ]:
lowest_Unemployment_country = df.loc[df['Unemployment'].idxmin()]['country']
print(f'lowest Unemployment country : {lowest_Unemployment_country}')

In [ ]:
# Filter rows for 'India'
India_df = df[df['country'] == 'India']
India_Unemployment = India_df[['country', 'Year', 'Unemployment']].sort_values(by='Unemployment', ascending=True).head(19)
India_Unemployment

In [ ]:
# Filter rows for 'India'
India_df = df[df['country'] == 'India']
India_Unemployment = India_df[['country', 'Year', 'Unemployment']].sort_values(by='Unemployment', ascending=False).head(19)
India_Unemployment

In [ ]:
# 1. Filter rows for 'India & Pakistan'
India_df = df[df['country'] == 'India']
Pak_df = df[df['country'] == 'Pakistan']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
India_df = India_df[India_df['Year'].isin(years)]
Pak_df = Pak_df[Pak_df['Year'].isin(years)]

# 3. Create a line plot for Unemployment over the years
plt.figure(figsize=(16, 6))
plt.plot(India_df['Year'].values, India_df['Unemployment'].values, marker='o', linestyle='-', color='magenta', label='India')
plt.plot(India_df['Year'].values, Pak_df['Unemployment'].values, marker='o', linestyle='-', color='green', label='Pakistan')
plt.title('Unemployment comparison between India & Pakistan (2001-2019)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Unemployment Rate', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()
plt.tight_layout()
plt.show()

In [ ]:
# 1. Filter rows for 'Japan, USA, China, India, UK, France'
Japan_df = df[df['country'] == 'Japan']
China_df = df[df['country'] == 'China']
USA_df = df[df['country'] == 'United States']
India_df = df[df['country'] == 'India']
UK_df = df[df['country'] == 'United Kingdom']
france_df = df[df['country'] == 'France']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
Japan_df = Japan_df[Japan_df['Year'].isin(years)]
China_df = China_df[China_df['Year'].isin(years)]
USA_df = USA_df[USA_df['Year'].isin(years)]
India_df = India_df[India_df['Year'].isin(years)]
UK_df = UK_df[UK_df['Year'].isin(years)]
france_df = france_df[france_df['Year'].isin(years)]

# 3. Create a line plot for Life Expectancy over the years
plt.figure(figsize=(20, 10))
plt.plot(Japan_df['Year'].values, Japan_df['Unemployment'].values, marker='o', linestyle='-', color='green', label='Japan')
plt.plot(Japan_df['Year'].values, China_df['Unemployment'].values, marker='o', linestyle='-', color='purple', label='China')
plt.plot(Japan_df['Year'].values, USA_df['Unemployment'].values, marker='o', linestyle='-', color='olive', label='USA')
plt.plot(Japan_df['Year'].values, India_df['Unemployment'].values, marker='o', linestyle='-', color='blue', label='India')
plt.plot(Japan_df['Year'].values, UK_df['Unemployment'].values, marker='o', linestyle='-', color='cyan', label='United Kingdom')
plt.plot(Japan_df['Year'].values, france_df['Unemployment'].values, marker='o', linestyle='-', color='magenta', label='France')
plt.title('Unemployment comparison of Japan, China, USA, India, UK & France  (2001-2019)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Unemployment', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()   # Add legend to distinguish between Japan and India
plt.tight_layout()
plt.show()

In [ ]:
# Create a bar graph
sns.set_style('darkgrid')
plt.figure(figsize=(16,10))
data=df.sort_values(by='Unemployment', ascending=True).head(300)
sns.barplot(y='country', x='Unemployment', data=data)
plt.xlabel('Unemployment ', color='green', size=40)
plt.ylabel('Country', color='green', size=40)
plt.title('Unemployment data for each Country', color='red',size=40)

# Education Expenditure

In [ ]:
highest_Education_Expenditure_country = df[['country', 'Year', 'Education Expenditure %']].sort_values(by='Education Expenditure %', ascending=False).head(5)
highest_Education_Expenditure_country

In [ ]:
highest_Education_Expenditure_country = df.loc[df['Education Expenditure %'].idxmax()]['country']
print(f'highest Education Expenditure country : {highest_Education_Expenditure_country}')

In [ ]:
lowest_Education_Expenditure_country = df[['country', 'Year', 'Education Expenditure %']].sort_values(by='Education Expenditure %', ascending=True).head(5)
lowest_Education_Expenditure_country

In [ ]:
lowest_Education_Expenditure_country = df.loc[df['Education Expenditure %'].idxmin()]['country']
print(f'lowest Education Expenditure country : {lowest_Education_Expenditure_country}')

In [ ]:
# 1. Filter rows for 'India & Pakistan'
India_df = df[df['country'] == 'India']
Pak_df = df[df['country'] == 'Pakistan']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
India_df = India_df[India_df['Year'].isin(years)]
Pak_df = Pak_df[Pak_df['Year'].isin(years)]

# 3. Create a line plot for Education Expenditure over the years
plt.figure(figsize=(16, 6))
plt.plot(India_df['Year'].values, India_df['Education Expenditure %'].values, marker='o', linestyle='-', color='magenta', label='India')
plt.plot(India_df['Year'].values, Pak_df['Education Expenditure %'].values, marker='o', linestyle='-', color='green', label='Pakistan')
plt.title('Education Expenditure comparison between India & Pakistan (2001-2019)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Education Expenditure %', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()
plt.tight_layout()
plt.show()

In [ ]:
# 1. Filter rows for 'Japan, USA, China, India, UK, France'
Japan_df = df[df['country'] == 'Japan']
USA_df = df[df['country'] == 'United States']
China_df = df[df['country'] == 'China']
India_df = df[df['country'] == 'India']
UK_df = df[df['country'] == 'United Kingdom']
france_df = df[df['country'] == 'France']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
Japan_df = Japan_df[Japan_df['Year'].isin(years)]
China_df = China_df[China_df['Year'].isin(years)]
USA_df = USA_df[USA_df['Year'].isin(years)]
India_df = India_df[India_df['Year'].isin(years)]
UK_df = UK_df[UK_df['Year'].isin(years)]
france_df = france_df[france_df['Year'].isin(years)]

# 3. Create a line plot for CO2 Emission over the years
plt.figure(figsize=(16, 6))
plt.plot(Japan_df['Year'].values, Japan_df['Education Expenditure %'].values, marker='o', linestyle='-', color='green', label='Japan')
plt.plot(USA_df['Year'].values, USA_df['Education Expenditure %'].values, marker='o', linestyle='-', color='purple', label='USA')
plt.plot(China_df['Year'].values, China_df['Education Expenditure %'].values, marker='o', linestyle='-', color='blue', label='China')
plt.plot(India_df['Year'].values, India_df['Education Expenditure %'].values, marker='o', linestyle='-', color='orange', label='India')
plt.plot(Japan_df['Year'].values, UK_df['Education Expenditure %'].values, marker='o', linestyle='-', color='cyan', label='United Kingdom')
plt.plot(Japan_df['Year'].values, france_df['Education Expenditure %'].values, marker='o', linestyle='-', color='magenta', label='France')
plt.title('Education Expenditure of Japan, USA, China, India, UK & France (2001-20219)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Education Expenditure %', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()   # Add legend to distinguish between Japan, USA, China and India
plt.tight_layout()
plt.show()

In [ ]:
# Create a bar graph
sns.set_style('darkgrid')
plt.figure(figsize=(16,10))
data=df.sort_values(by='Education Expenditure %', ascending=False).head(300)
sns.barplot(y='country', x='Education Expenditure %', data=data)
plt.xlabel('Education Expenditure ', color='green', size=40)
plt.ylabel('Country', color='green', size=40)
plt.title('Education Expenditure data for each Country', color='red',size=40)

# Health Expenditure

In [ ]:
highest_Health_Expenditure_country = df[['country', 'Year', 'Health Expenditure %']].sort_values(by='Health Expenditure %', ascending=False).head(5)
highest_Health_Expenditure_country

In [ ]:
highest_Health_Expenditure_country = df.loc[df['Health Expenditure %'].idxmax()]['country']
print(f'Maximum Health Expenditure country : {highest_Health_Expenditure_country}')

In [ ]:
lowest_Health_Expenditure_country = df[['country', 'Year', 'Health Expenditure %']].sort_values(by='Health Expenditure %', ascending=True).head(5)
lowest_Health_Expenditure_country

In [ ]:
lowest_Health_Expenditure_country = df.loc[df['Health Expenditure %'].idxmin()]['country']
print(f'Minimum Health Expenditure country : {lowest_Health_Expenditure_country}')

In [ ]:
# 1. Filter rows for 'India & Pakistan'
India_df = df[df['country'] == 'India']
Pak_df = df[df['country'] == 'Pakistan']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
India_df = India_df[India_df['Year'].isin(years)]
Pak_df = Pak_df[Pak_df['Year'].isin(years)]

# 3. Create a line plot for Health Expenditure over the years
plt.figure(figsize=(16, 6))
plt.plot(India_df['Year'].values, India_df['Health Expenditure %'].values, marker='o', linestyle='-', color='magenta', label='India')
plt.plot(India_df['Year'].values, Pak_df['Health Expenditure %'].values, marker='o', linestyle='-', color='green', label='Pakistan')
plt.title('Health Expenditure comparison between India & Pakistan (2001-2019)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Health Expenditure %', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()
plt.tight_layout()
plt.show()

In [ ]:
# 1. Filter rows for 'Japan, USA, China, India, UK, France'
Japan_df = df[df['country'] == 'Japan']
USA_df = df[df['country'] == 'United States']
China_df = df[df['country'] == 'China']
India_df = df[df['country'] == 'India']
UK_df = df[df['country'] == 'United Kingdom']
france_df = df[df['country'] == 'France']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
Japan_df = Japan_df[Japan_df['Year'].isin(years)]
China_df = China_df[China_df['Year'].isin(years)]
USA_df = USA_df[USA_df['Year'].isin(years)]
India_df = India_df[India_df['Year'].isin(years)]
UK_df = UK_df[UK_df['Year'].isin(years)]
france_df = france_df[france_df['Year'].isin(years)]

# 3. Create a line plot for CO2 Emission over the years
plt.figure(figsize=(16, 6))
plt.plot(Japan_df['Year'].values, Japan_df['Health Expenditure %'].values, marker='o', linestyle='-', color='green', label='Japan')
plt.plot(USA_df['Year'].values, USA_df['Health Expenditure %'].values, marker='o', linestyle='-', color='purple', label='USA')
plt.plot(China_df['Year'].values, China_df['Health Expenditure %'].values, marker='o', linestyle='-', color='blue', label='China')
plt.plot(India_df['Year'].values, India_df['Health Expenditure %'].values, marker='o', linestyle='-', color='orange', label='India')
plt.plot(Japan_df['Year'].values, UK_df['Health Expenditure %'].values, marker='o', linestyle='-', color='cyan', label='United Kingdom')
plt.plot(Japan_df['Year'].values, france_df['Health Expenditure %'].values, marker='o', linestyle='-', color='magenta', label='France')
plt.title('Health Expenditure of Japan, USA, China, India, UK & France (2001-20219)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Health Expenditure %', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()   # Add legend to distinguish between Japan, USA, China, UK, France & India
plt.tight_layout()
plt.show()

In [ ]:
# Create a bar graph
sns.set_style('darkgrid')
plt.figure(figsize=(16,10))
data=df.sort_values(by='Health Expenditure %', ascending=False).head(400)
sns.barplot(y='country', x='Health Expenditure %', data=data)
plt.xlabel('Health Expenditure ', color='green', size=40)
plt.ylabel('Country', color='green', size=40)
plt.title('Health Expenditure data for each Country', color='red',size=40)

# CO2 Emission

In [ ]:
highest_CO2_emission_country = df[['country', 'Year', 'CO2']].sort_values(by='CO2', ascending=False).head(5)
highest_CO2_emission_country

In [ ]:
Maximum_CO2_emission_country = df.loc[df['CO2'].idxmax()]['country']
print(f'Maximum CO2 Emission country : {Maximum_CO2_emission_country}')

In [ ]:
lowest_CO2_emission_country = df[['country', 'Year', 'CO2']].sort_values(by='CO2', ascending=True).head(5)
lowest_CO2_emission_country

In [ ]:
Minimum_CO2_emission_country = df.loc[df['CO2'].idxmin()]['country']
print(f'Minimum CO2 Emission country : {Minimum_CO2_emission_country}')

In [ ]:
# 1. Filter rows for 'India & Pakistan'
India_df = df[df['country'] == 'India']
Pak_df = df[df['country'] == 'Pakistan']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
India_df = India_df[India_df['Year'].isin(years)]
Pak_df = Pak_df[Pak_df['Year'].isin(years)]

# 3. Create a line plot for CO2 emission over the years
plt.figure(figsize=(16, 6))
plt.plot(India_df['Year'].values, India_df['CO2'].values, marker='o', linestyle='-', color='magenta', label='India')
plt.plot(India_df['Year'].values, Pak_df['CO2'].values, marker='o', linestyle='-', color='green', label='Pakistan')
plt.title('CO2 Emission comparison between India & Pakistan (2001-2019)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('CO2 Emission', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()
plt.tight_layout()
plt.show()

In [ ]:
# 1. Filter rows for 'Japan, USA, China, India, UK, France'
Japan_df = df[df['country'] == 'Japan']
USA_df = df[df['country'] == 'United States']
China_df = df[df['country'] == 'China']
India_df = df[df['country'] == 'India']
UK_df = df[df['country'] == 'United Kingdom']
france_df = df[df['country'] == 'France']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
Japan_df = Japan_df[Japan_df['Year'].isin(years)]
China_df = China_df[China_df['Year'].isin(years)]
USA_df = USA_df[USA_df['Year'].isin(years)]
India_df = India_df[India_df['Year'].isin(years)]
UK_df = UK_df[UK_df['Year'].isin(years)]
france_df = france_df[france_df['Year'].isin(years)]

# 3. Create a line plot for CO2 Emission over the years
plt.figure(figsize=(16, 6))
plt.plot(Japan_df['Year'].values, Japan_df['CO2'].values, marker='o', linestyle='-', color='green', label='Japan')
plt.plot(USA_df['Year'].values, USA_df['CO2'].values, marker='o', linestyle='-', color='purple', label='USA')
plt.plot(China_df['Year'].values, China_df['CO2'].values, marker='o', linestyle='-', color='blue', label='China')
plt.plot(India_df['Year'].values, India_df['CO2'].values, marker='o', linestyle='-', color='orange', label='India')
plt.plot(Japan_df['Year'].values, UK_df['CO2'].values, marker='o', linestyle='-', color='cyan', label='United Kingdom')
plt.plot(Japan_df['Year'].values, france_df['CO2'].values, marker='o', linestyle='-', color='magenta', label='France')
plt.title('CO2 Emission of Japan, USA, China, India, UK & France (2001-20219)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('CO2 Emission', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()   # Add legend to distinguish between Japan, USA, China, UK, France & India
plt.tight_layout()
plt.show()

In [ ]:
# Create a bar graph
sns.set_style('darkgrid')
plt.figure(figsize=(16,10))
data=df.sort_values(by='CO2', ascending=False).head(500)
sns.barplot(y='country', x='CO2', data=data)
plt.xlabel('CO2 ', color='green', size=40)
plt.ylabel('Country', color='green', size=40)
plt.title('CO2 data for each Country', color='red',size=40)

# Corruption Analysis

In [ ]:
highest_Corruption_country = df[['country', 'Year', 'Corruption']].sort_values(by='Corruption', ascending=False).head(5)
highest_Corruption_country

In [ ]:
highest_corruption_country = df.loc[df['Corruption'].idxmax()]['country']
print(f'Maximum Corrupted country : {highest_corruption_country}')

In [ ]:
lowest_Corruption_country = df[['country', 'Year', 'Corruption']].sort_values(by='Corruption', ascending=True).head(5)
lowest_Corruption_country

In [ ]:
lowest_corruption_country = df.loc[df['Corruption'].idxmin()]['country']
print(f'Minimum Corrupted country : {lowest_corruption_country}')

In [ ]:
# 1. Filter rows for 'India & Pakistan'
India_df = df[df['country'] == 'India']
Pak_df = df[df['country'] == 'Pakistan']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
India_df = India_df[India_df['Year'].isin(years)]
Pak_df = Pak_df[Pak_df['Year'].isin(years)]

# 3. Create a line plot for Corruption over the years
plt.figure(figsize=(16, 6))
plt.plot(India_df['Year'].values, India_df['Corruption'].values, marker='o', linestyle='-', color='magenta', label='India')
plt.plot(India_df['Year'].values, Pak_df['Corruption'].values, marker='o', linestyle='-', color='green', label='Pakistan')
plt.title('Corruption comparison between India & Pakistan (2001-2019)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Corruption', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()
plt.tight_layout()
plt.show()

In [ ]:
# Create a bar graph
sns.set_style('darkgrid')
plt.figure(figsize=(16,10))
data=df.sort_values(by='Corruption', ascending=False).head(400)
sns.barplot(y='country', x='Corruption', data=data)
plt.xlabel('Corruption ', color='green', size=40)
plt.ylabel('Country', color='green', size=40)
plt.title('Corruption data for each Country', color='red',size=40)

# Injuries

In [ ]:
highest_Injuries_country = df[['country', 'Year', 'Injuries']].sort_values(by='Injuries', ascending=False).head(5)
highest_Injuries_country

In [ ]:
highest_Injuries_country = df.loc[df['Injuries'].idxmax()]['country']
print(f'Maximum Injuries country : {highest_Injuries_country}')

In [ ]:
lowest_Injuries_country = df[['country', 'Year', 'Injuries']].sort_values(by='Injuries', ascending=True).head(5)
lowest_Injuries_country

In [ ]:
lowest_Injuries_country = df.loc[df['Injuries'].idxmin()]['country']
print(f'Minimum Injuries country : {lowest_Injuries_country}')

In [ ]:
# Create a bar graph
sns.set_style('darkgrid')
plt.figure(figsize=(16,10))
data=df.sort_values(by='Injuries', ascending=False).head(600)
sns.barplot(y='country', x='Injuries', data=data)
plt.xlabel('Injuries ', color='green', size=40)
plt.ylabel('Country', color='green', size=40)
plt.title('Injuries data for each Country', color='red',size=40)

# Undernourishment Comparison among Japan, china, USA, India

In [ ]:
# Create a bar graph
sns.set_style('darkgrid')
plt.figure(figsize=(16,10))
data=df.sort_values(by='Prevelance of Undernourishment', ascending=False).head(500)
sns.barplot(y='country', x='Prevelance of Undernourishment', data=data)
plt.xlabel('Prevelance of Undernourishment ', color='green', size=40)
plt.ylabel('Country', color='green', size=40)
plt.title('Undernourishment data for each Country', color='red',size=40)

In [ ]:
# 1. Filter rows for 'Japan, USA, China, India, UK, France'
Japan_df = df[df['country'] == 'Japan']
USA_df = df[df['country'] == 'United States']
China_df = df[df['country'] == 'China']
India_df = df[df['country'] == 'India']
UK_df = df[df['country'] == 'United Kingdom']
france_df = df[df['country'] == 'France']

# 2. Filter rows for years from 2001 to 2019
years = range(2001, 2019)
Japan_df = Japan_df[Japan_df['Year'].isin(years)]
China_df = China_df[China_df['Year'].isin(years)]
USA_df = USA_df[USA_df['Year'].isin(years)]
India_df = India_df[India_df['Year'].isin(years)]
UK_df = UK_df[UK_df['Year'].isin(years)]
france_df = france_df[france_df['Year'].isin(years)]

# 3. Create a line plot for CO2 Emission over the years
plt.figure(figsize=(16, 6))
plt.plot(Japan_df['Year'].values, Japan_df['Prevelance of Undernourishment'].values, marker='o', linestyle='-', color='green', label='Japan')
plt.plot(Japan_df['Year'].values, USA_df['Prevelance of Undernourishment'].values, marker='o', linestyle='-', color='purple', label='USA')
plt.plot(Japan_df['Year'].values, China_df['Prevelance of Undernourishment'].values, marker='o', linestyle='-', color='blue', label='China')
plt.plot(Japan_df['Year'].values, India_df['Prevelance of Undernourishment'].values, marker='o', linestyle='-', color='orange', label='India')
#plt.plot(Japan_df['Year'].values, UK_df['Prevelance of Undernourishment'].values, marker='o', linestyle='-', color='cyan', label='United Kingdom')
#plt.plot(Japan_df['Year'].values, france_df['Prevelance of Undernourishment'].values, marker='o', linestyle='-', color='magenta', label='France')
plt.title('Prevelance of Undernourishment of Japan, USA, China, India (2001-20219)', color='red', size=25)
plt.xlabel('Year', color='blue', size=20)
plt.ylabel('Prevelance of Undernourishment', color='blue', size=20)
plt.grid(True)
plt.xticks(years, rotation=0)
plt.legend()   # Add legend to distinguish between Japan, USA, China and India
plt.tight_layout()
plt.show()

# Thank you!